name: fluo
description: Authentication made for Flutter. Complete UI flows in less than 5 minutes.
version: 3.3.3
homepage: https://fluo.dev
repository: https://github.com/fluo-dev/flutter-sdk

environment:
  sdk: ">=3.5.1 <4.0.0"
  flutter: ">=3.8.0"

platforms:
  android:
  ios:
  web:
  macos:

topics:
  - authentication
  - authentication-sdk
  - user-onboarding
  - user-registration
  - social-login

dependencies:
  country_flags: ^4.1.0
  device_region: ^1.4.0
  diacritic: ^0.1.6
  flutter:
    sdk: flutter
  flutter_libphonenumber: ^2.5.1
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.2.2
  google_sign_in: ^6.3.0
  google_sign_in_web: ^0.12.4+4
  http: ^1.2.2
  in_app_review: ^2.0.11
  intl: ^0.20.2
  pinput: ^5.0.0
  provider: ^6.1.2
  shared_preferences: ^2.5.3
  sign_in_with_apple: ^7.0.1
  styled_text: ^8.1.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  assets:
    - assets/images/
